# Generated by Django 5.0.6 on 2024-12-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
