# Generated by Django 5.0.6 on 2024-11-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jojo_api', '0002_rename_description_character_power_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('mal_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='charactervote',
            name='character',
        ),
        migrations.RemoveField(
            model_name='charactervote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='theory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='theorylike',
            name='theory',
        ),
        migrations.RemoveField(
            model_name='theorylike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='character',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='character',
            name='power_description',
        ),
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.CharField(default='Inconnu', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='jojo_api.part'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ArchivedItem',
        ),
        migrations.DeleteModel(
            name='CharacterVote',
        ),
        migrations.DeleteModel(
            name='Theory',
        ),
        migrations.DeleteModel(
            name='TheoryLike',
        ),
    ]
